{
 "title": "Web monitor",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Web alive",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_success{job=~\"blackbox-web\"}) * 100"
    }
   ]
  },
  {
   "title": "Connection failure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{job=~\"blackbox-web\"} == 0)"
    }
   ]
  },
  {
   "title": "Web by HTTPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_http_ssl{job=~\"blackbox-web\"} != 0)"
    }
   ]
  },
  {
   "title": "Web by HTTP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_http_ssl{job=~\"blackbox-web\"} == 0)"
    }
   ]
  },
  {
   "title": "SSL cert. neary expired",
   "type": "singlestat",
   "description": "Monitor ssl cert expired within 30 days",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_ssl_earliest_cert_expiry{job=~\"blackbox-web\"} - time() < 86400 * 30)"
    }
   ]
  },
  {
   "title": "HTTP last status code",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "probe_http_status_code{job=~\"blackbox-web\"}"
    }
   ]
  },
  {
   "title": "Duration time query",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~\"blackbox-web\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS lookup times delay",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{job=~\"blackbox-web\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}