{
 "title": "Alert Summary",
 "tags": [
  "prometheus",
  "alert",
  "notification"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Summary host unavailable",
   "type": "singlestat",
   "description": "Display number of host isn't scrape data with prometheus.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (count(up == 0) / count(up))"
    }
   ]
  },
  {
   "title": "Summary of critical alert",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{severity=~\"critical\"})"
    }
   ]
  },
  {
   "title": "Summary of major alert",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{severity=~\"major\"})"
    }
   ]
  },
  {
   "title": "Summary of minor alert",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{severity=~\"minor\"})"
    }
   ]
  },
  {
   "title": "Total firing message",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Total pending message",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\"})"
    }
   ]
  },
  {
   "title": "Alert on Prometheus",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "ALERTS", "legendFormat": "state" }
   ]
  },
  { "title": "Alert list on Grafana", "type": "alertlist", "gridPos": { "h": 13, "w": 6, "x": 0, "y": 13 } }
 ]
}