{
 "title": "Demo2 - Tomcat monitor",
 "description": "Tomcat dashboard using metrics from prometheus JMX exporter",
 "tags": [ "Tomcat8" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(tomcat_info, job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(tomcat_info,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server info",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_info{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Protocol [$protocol]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "protocol" },
  {
   "title": "Active threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(tomcat_threads_active_total{job=\"$job\",instance=\"$instance\",name=\"http-nio-8080\"})"
    }
   ]
  },
  {
   "title": "Max threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(tomcat_threads_max{job=\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Java daemon threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_threads_daemon{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Java current threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Java deadlock threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_threads_deadlocked{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Traffic send/recv",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "idelta(tomcat_requestprocessor_sent_bytes{job=\"$job\",instance=\"$instance\",name=\"http-nio-8080\"}[2m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "idelta(tomcat_requestprocessor_received_bytes{job=\"$job\",instance=\"$instance\",name=\"http-nio-8080\"}[2m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Request  count / error count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(tomcat_requestprocessor_request_count{job=\"$job\",instance=\"$instance\",name=\"http-nio-8080\"}[2m])",
     "legendFormat": "Request {{protocol}}[{{port}}]"
    },
    {
     "expr": "idelta(tomcat_requestprocessor_error_count{job=\"$job\",instance=\"$instance\",name=\"http-nio-8080\"}[2m])",
     "legendFormat": "Error {{protocol}}[{{port}}]"
    }
   ]
  },
  { "title": "Servlet Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Session count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(tomcat_session_created_total{job=\"$job\",instance=\"$instance\"}[2m])) by (instance)",
     "legendFormat": "New"
    },
    {
     "expr": "sum(idelta(tomcat_session_expired_total{job=\"$job\",instance=\"$instance\"}[2m])) by (instance)",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(idelta(tomcat_session_rejected_total{job=\"$job\",instance=\"$instance\"}[2m])) by (instance)",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Session current count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_session_active_total{job=\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Session alivetime avg",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_session_alivetime_seconds_avg{job=\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Session total expired",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_session_expired_total{job=\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Top 5 servlet request count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, idelta(servlet_request_seconds_count{job=\"$job\",instance=\"$instance\"}[2m]))",
     "legendFormat": "context={{context}} , method={{method}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet response status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, idelta(servlet_response_status_total{job=\"$job\",instance=\"$instance\"}[2m]))",
     "legendFormat": "context:{{context}} , status:{{status}}"
    }
   ]
  },
  {
   "title": "Top 5 servlets average processing time per request",
   "type": "graph",
   "description": "Top 4 servlets average processing time per request in last 5 minutes",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(5, idelta(servlet_request_seconds_count{job=\"$job\",instance=\"$instance\"}[2m]) / idelta(servlet_request_seconds_sum{job=\"$job\",instance=\"$instance\"}[2m]))",
     "legendFormat": "context:{{context}} , method:{{method}}"
    }
   ]
  }
 ]
}