global:
  scrape_interval:     15s
  evaluation_interval: 1m
  external_labels:
    monitor: 'melody-prom'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'localhost'
    static_configs:
      - targets: ['node-exporter:9100']