global:
  scrape_interval:     15s
  evaluation_interval: 1m
  external_labels:
    monitor: 'melody-prom'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'VMHost'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx_get]
    static_configs:
      - targets:
          - "https://www.opsta.co.th/"
          - "https://git.opsta.io"
          - "http://simple_http1:8000"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115